server:
  port: 8090
spring:
  application:
    name: ecommerce
  config:
    activate:
      on-profile:
        - default
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: kanimozhi123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: POSTGRESQL